name := "Thesis-cassandra-spark"
organization := "TUDELFT"
version := "0.0.1"
scalaVersion := "2.10.5"
libraryDependencies += "com.datastax.spark" %% "spark-cassandra-connector" % "1.2.1"
libraryDependencies += "org.apache.spark" %% "spark-core" % "1.2.2" % "provided"
libraryDependencies += "org.apache.spark" %% "spark-graphx" % "1.2.2" % "provided"
